name = "Hugunica"
license = "Apache-2.0"
licenselink = "https://github.com/michaelskyba/hugunica/blob/main/LICENSE"
description = "The Dragon (Hugo) Theme of Hugunica"
min_version = "0.41.0"

[author]
  name = "sucralose"
  homepage = "https://veilm.github.io"
